### ISSUE TITLE
Screenshotssss

### ISSUE THREAD

**Issue by rapfl** [rapfl/polarstern#4]
Aktueller Draft >> https://laughing-rosalind-2cbfee.netlify.com/

## TODO v1

- [x] Telefonnummern validieren
- [x] Parallax effect on screenshots
- [x] Font-Weights anpassen
- [x] Font-Color dunkel: #122F3A
- [x] Franz-Abschnitt: Ein solid color Block mit drei Rubriken, die Jeweils Icon (Emojis), Heading (wie z.B. "Mutige Entscheidungen") und Paragraph (kurze Beschreibung wie in der aktuellen Version auch) haben
- [x] Footer reparieren (Max-Height?)
- [x] Screenshots section: minimal die Textpassagen schöner machen, maximal rumspielen mit den einzelnen Abschnitten und schöne Boxen draus bauen
- [x] Zweiten CTA vor den Footer
- [x] Für Mobile: SUBMIT-Button über den gesamten Viewport, 1. Screenshot 
- [x] Texte Updaten
- [x] Neues Logo in den Footer
- [x] Über Polarstern-Section einfügen

---

- [x] Texte überarbeiten und ins Spreadsheet hochladen
- [x] Bilder finden für den Hintergrund (falls notwendig)

### Screenshots
[Hier die **ausgewählten** Screens auf G Drive
](https://drive.google.com/drive/u/0/folders/1prt5tucWosB851nZUL_0h9qscAcr-vyb)

### Wireframe
So *könnte* das ganze Aussehen in meiner Vorstellung, wenn du Ideen hast umso besser 👍 
I. und II. sind Alternativen, bei II. ist ein Carousel oder irgendwas.
![wireframe ps lp](https://user-images.githubusercontent.com/45067753/51901034-03211d80-23b7-11e9-98a7-3a2bd3deab7c.jpeg)
